name: Tenants

on:
  push:
    branches: [ release-tenants ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Vapor rename
        run: |
            mv vapor.tenants.yml vapor.yml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
      - name: Install Project Dependencies
        run: composer update
      - name: Deploy Environment
        run: vapor deploy tenants
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}